<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>254b3a55-6d79-4d0a-adac-631608b5226c</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TaskTrackerSystem.Application\TaskTrackerSystem.Application.csproj" />
    <ProjectReference Include="..\TaskTrackerSystem.Infrastructure\TaskTrackerSystem.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.18">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
